### ISSUE TITLE
[NEOS Discovery] Error emailing records

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#100] opened 2018-05-01 18:55 UTC
When I try to email a record, I get "Incomplete response received from application".

**Comment by redlibrarian** [comment] 2018-05-01 18:55
Investigating...

**Comment by redlibrarian** [comment] 2018-05-10 15:31
This should be working in the next release (this morning).

**Comment by Andeebee** [comment] 2018-07-20 12:30
No email - from record or from bookmarks

**Comment by redlibrarian** [comment] 2018-07-20 14:10
I suspect this is connected to the network issue affecting SMS. I think we made a network change at some point that is preventing emails/SMSs from going out (this is also affecting UAL Discovery). Our sysadmin is investigating.

**Comment by redlibrarian** [comment] 2018-07-20 16:04
@Andeebee I just tried this and it worked for me (email, but not SMS).

**Comment by seanluyk** [comment] 2018-10-18 18:18
Confirmed that this is working off campus, closing

**Comment by Andeebee** [comment] 2018-10-18 19:43
Did it take a while to come in? I've tried twice this morning with no luck.

**Comment by seanluyk** [comment] 2018-10-18 19:50
@Andeebee not for me - I was testing off of Wifi, and the email was received within seconds.

**Comment by seanluyk** [comment] 2018-10-18 19:50
@Andeebee maybe double check your SPAM folder?

**Comment by Andeebee** [comment] 2018-10-18 20:37
Doesn't seem to have turned up, even in SPAM.

**Comment by seanluyk** [comment] 2018-10-18 21:00
Thanks for testing @Andeebee  - we'll keep this one open and investigate

**Comment by seanluyk** [comment] 2018-10-25 19:39
Will only send to a UofA email address

**Comment by Andeebee** [comment] 2018-10-26 17:33
Emails that we tested yesterday at 1:30 pm -- came through my hotmail account at 4:30, my work account this morning at 11, and personal gmail a few minutes ago. Tried to send another to gmail, but it hasn't come through yet.

**Comment by seanluyk** [comment] 2018-10-26 17:37
@Andeebee thanks, we've made some changes and it seems to be working better, but not perfectly. Please continue to test email and SMS and report any results here. In my testing, I've been able to get it to work instantly to my personal Gmail and cellphone

**Comment by seanluyk** [comment] 2018-10-29 20:36
Closing.

**Comment by seanluyk** [comment] 2018-10-29 20:36
Reclosing

**Closed by seanluyk** 2018-10-29 20:36 UTC
Labels: High Priority
