### ISSUE TITLE
[NEOSDiscovery] Institution Branding Converts to NEOS Branding

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#107] opened 2018-05-10 14:26 UTC
Different actions that trigger the change:

- Using the exposed Subject headings in the record to browse.
- Letting a record sit idle, and using the previous, next links.

**Comment by redlibrarian** [comment] 2018-05-10 14:58
@nnunn Can you take a look at this one? I think the subjects may just need the institutional parameter added to the links; this may be true of previous, next as well. As for letting the record sit idle, this may be a problem with the way we've implemented the variable and might need further investigation.

**Comment by nnunn** [comment] 2018-05-10 15:01
Yup I'll look at this.

**Comment by nnunn** [comment] 2018-05-10 15:09
This is half done - the subjects now work. However, I think we will need to dig in a little to the record sitting idle problem (next and previous do work, unless the record is idle)

**Comment by redlibrarian** [comment] 2018-05-10 15:53
I have an idea of how we might solve this (set local variable to contents of global variable on page load).

**Comment by redlibrarian** [comment] 2018-07-17 18:19
I've fixed this in dev, but it's hard to test with only a single user. We'll have to deploy and see what it looks like live.

**Comment by redlibrarian** [comment] 2018-07-23 19:42
Hm. We saw this break in our meeting at Friday, but I can't get it to break now. It's going to be hard to test, hard to see if something fixes it...

**Comment by redlibrarian** [comment] 2018-07-27 16:48
We'll have to keep an eye on this and revisit at some point. Maybe with more people using it we can get a better sense of what's still triggering it.

**Comment by nnunn** [comment] 2018-08-22 20:06
Any further reports of this issue? I can't reproduce it on my machine.

**Comment by paulpype-goa** [comment] 2018-08-23 15:41
I have just reproduced this a couple of times--you need two users or two browsers. In order to make sure that I'm actually seeing this issue, I cleared my cookies and used two libraries I wouldn't otherwise use. The steps are roughly as follows:

1. Search catalogue (library A) in one browser. (You may have to click into a search result to reproduce the issue.)
2. Search catalogue (library B) in another browser or on another computer. (Again, you may have to click into a search result to reproduce the issue.)
3. Back on first browser/computer, click into another search result or click on Next >> link. Instead of branding for library A, you _may_ see branding for library B.

A couple of times, I've also see the branding revert to the NEOS branding when clicking on a result from a hit list when I didn't have a second session going.

If the issues is as I suspect--branding is transferring from one user session to another, it should be fairly easy to isolate and reproduce now, but it will be chaos once users are actively using the catalogue.

**Comment by nnunn** [comment] 2018-08-23 15:47
Great! Now I can reproduce the problem which is a huge step towards solving it. I'm going to work on this today and hopefully finally put it bed. Thanks so much!

**Comment by Andeebee** [comment] 2018-08-23 16:16
!!! Great !!!
Just one point to addition point to add about the NEOS branding. If you select one of the author or series  links within a record, the search that it runs is a generic NEOS catalogue search that doesn't pull lib= into the search query like the open subject links do.

**Comment by seanluyk** [comment] 2018-09-14 20:48
This is still occurring in author links, possibly other places

**Comment by nnunn** [comment] 2018-09-21 18:04
Ok I'm going to work on this again.

**Comment by seanluyk** [comment] 2018-09-27 18:21
@Andeebee I think this is fixed, please test

**Comment by Andeebee** [comment] 2018-09-27 20:10
1. Confirmed that all link outs within the record (series, author) are now pulling the lib= to the URL.
2. Continuing to have libraries switch during a session.

**Comment by Andeebee** [comment] 2018-09-27 21:17
Good question - tested again to confirm. 
I didn't see any random branding changes. It was just the linking that was randomly changing the lib in the URL over the course of a session.

**Closed** 2018-10-12 19:28 UTC
Labels: High Priority, bug, development required
